### PR TITLE
Support for PocketMine-MP 5.0

### PR DESCRIPTION
**Pull request by fernanACM**
**New implementations:**
* A new configuration has been added in "config.yml". 
> which allows you to edit the plugin prefix, there is also a function that serves to deactivate and activate the collision when restarting a mine.

 * Check for new versions for the config.yml

 * Support for configuration of old mines.
 > This will make the numeric ID adapt to the letter ID.

### CODE REVIEW

**Comment by KingOfTurkey38** [comment]
Has this been tested properly?

**Comment by fernanACM** [comment]
> Has this been tested properly?

Yes: https://www.youtube.com/watch?v=g7oCmQEKujg&lc=Ugw8xxIVyOtQVkP39_x4AaABAg&ab_channel=fernanACM


You just have to change the version of the virions and everything would be correct.

**Comment by KingOfTurkey38** [comment]
Looks like commando virion hasn't been updated yet so I'll wait for it to get updated then merge

**Comment by fernanACM** [comment]
> Looks like commando virion hasn't been updated yet so I'll wait for it to get updated then merge
[Updated virions](https://github.com/KingOfTurkey38/MineReset38/pull/15/commits/c3eb4ec6d5204e09d37fc2da308d627d6419a384)

**Comment by Pedhot-Dev** [comment]
> Looks like commando virion hasn't been updated yet so I'll wait for it to get updated then merge

Commando been updated, in github.com/Paroxity/Commando

**Pull request merged**
